name: Sample workflow for parallel jobs
on:
  push:
     branches:
        branch1

jobs:
  build:
   runs-on: ubuntu-latest
   name: Building gradle code
   steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v4
      with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
          cache: gradle
          cache-dependency-path:
             sub-project/*.gradle*
             sub-project/**/gradle-wrapper.properties
    - name: Build Gradle
      run: gradle build
  test:
    runs-on: ubuntu-latest
    name: Run test cases
    steps:
     - name: Checkout code
       uses: actions/checkout@v3
     - name: Set up JDK 11 for x64
       uses: actions/setup-java@v4
       with:
         java-version: '11'
         distribution: 'temurin'
         architecture: x64
     - name: Test 
       run: gradle test
       

       

      
        
